name=Verne_Code7448
version=1.0.0
author=Júlio Muanza Monteiro <juliomuanzam@gmail.com>
maintainer=Júlio Muanza Monteiro <juliomuanzam@gmail.com>
sentence=Biblioteca para controlar o decodificador 7448.
paragraph=Permite imprimir um digito, contagem progressiva e regressiva.
category=Device control
url=https://github.com/juliomuanzamonteiro/Verne_Code7448.git
architectures=*
